### ISSUE TITLE
Spianata

### ISSUE THREAD

**Issue by nclavaud** [lrqdo/charcut-ou-frometon#7]
Looks like charcut :pig:

**Comment by marcmillien** [comment]
Il est déjà dans la liste je crois https://github.com/lrqdo/charcut-ou-frometon/blob/8a308f37949b6c4c39d737a5923a2c8da2e98844/index.html#L68 :D

**Comment by nclavaud** [comment]
> Il est déjà dans la liste je crois

Cavolo !! :stuck_out_tongue_closed_eyes:
